type menuListParams = { title: string; content: string };
export const menuList: menuListParams[] = [
  { title: 'Моя работа', content: 'some content in this section' },
  { title: 'Структура портала', content: 'some content in this section' },
  { title: 'Личное расписание', content: 'some content in this section' },
  {
    title: 'Отсутствие на рабочем месте',
    content: 'some content in this section',
  },
  { title: 'Портфель услуг', content: 'some content in this section' },
  { title: 'Дашборды', content: 'some content in this section' },
  { title: 'Доски задач', content: 'some content in this section' },
  { title: 'Обращения', content: 'some content in this section' },
  { title: 'События', content: 'some content in this section' },
  { title: 'Инциденты', content: 'some content in this section' },
  { title: 'Проблемы', content: 'some content in this section' },
  { title: 'Настройка каталогов', content: 'some content in this section' },
  { title: 'Запросы на обслуживание', content: 'some content in this section' },
  { title: 'Запросы на изменение', content: 'some content in this section' },
  {
    title: 'Управление конфигурациями',
    content: 'some content in this section',
  },
  { title: 'Моя работа - 1', content: 'some content in this section' },
  { title: 'Структура портала - 1', content: 'some content in this section' },
  { title: 'Личное расписание - 1', content: 'some content in this section' },
  {
    title: 'Отсутствие на рабочем месте - 1',
    content: 'some content in this section',
  },
  { title: 'Настройка каталогов', content: 'some content in this section' },
  { title: 'Запросы на обслуживание', content: 'some content in this section' },
  { title: 'Запросы на изменение', content: 'some content in this section' },
  {
    title: 'Управление конфигурациями',
    content: 'some content in this section',
  },
  { title: 'Моя работа - 1', content: 'some content in this section' },
  { title: 'Структура портала - 1', content: 'some content in this section' },
  { title: 'Личное расписание - 1', content: 'some content in this section' },
  {
    title: 'Отсутствие на рабочем месте - 1',
    content: 'some content in this section',
  },
];
